'use client';

/* The parts a line, an area and a scatter all draw: the path through a series,
 * the points on it, and the marks those points become.
 *
 * Shared as a component rather than copied three times, because the thing that
 * has to be identical between them is not the appearance — it is which point a
 * reader lands on when they press the right arrow, and what it says when they do.
 */
import type { CSSProperties, ReactNode } from 'react';
import { line as d3line, area as d3area, curveLinear, curveMonotoneX } from 'd3-shape';
import { markerPath, seriesColour, seriesDash, seriesMarker } from './channel.js';
import { chartGeometry } from '../theme/chartTokens.js';
import { MARK_TARGET } from '../charts/target.js';
import styles from './Cartesian.module.scss';

export type ChartCurve = 'linear' | 'smooth';

const CURVES = { linear: curveLinear, smooth: curveMonotoneX };

export interface PlotPoint {
  x: number;
  y: number;
  /** The value at this point, already formatted. */
  label: string;
}

/** The path through a series' points, with gaps where there were none. */
export function seriesPath(points: readonly (PlotPoint | null)[], curve: ChartCurve): string {
  const generator = d3line<PlotPoint>()
    .defined((point) => point !== null)
    .x((point) => point.x)
    .y((point) => point.y)
    .curve(CURVES[curve]);
  return generator(points as PlotPoint[]) ?? '';
}

/**
 * The same path closed down to a baseline that moves — a stacked layer, whose
 * floor is the running total of the layers under it.
 *
 * Generated by `d3-shape` from a pair of accessors rather than by drawing the
 * top edge and walking a second path backwards. The backwards walk works for
 * straight segments and silently produces nonsense for a curve, because a
 * reversed cubic is not the same cubic with its points swapped.
 */
export function seriesBand(
  points: readonly (PlotPoint | null)[],
  floor: readonly number[],
  curve: ChartCurve,
): string {
  const generator = d3area<PlotPoint>()
    .defined((point) => point !== null)
    .x((point) => point.x)
    .y1((point) => point.y)
    .y0((_, index) => floor[index] ?? 0)
    .curve(CURVES[curve]);
  return generator(points as PlotPoint[]) ?? '';
}

/** The same path closed down to a baseline. */
export function seriesArea(
  points: readonly (PlotPoint | null)[], baseline: number, curve: ChartCurve,
): string {
  const generator = d3area<PlotPoint>()
    .defined((point) => point !== null)
    .x((point) => point.x)
    .y1((point) => point.y)
    .y0(baseline)
    .curve(CURVES[curve]);
  return generator(points as PlotPoint[]) ?? '';
}

export interface MarkProps {
  tabIndex: number;
  ref: (node: SVGGElement | null) => void;
  onFocus: () => void;
}

export interface PointMarksProps {
  points: readonly (PlotPoint | null)[];
  seriesIndex: number;
  seriesName: string;
  /** Category name per point, for the label. */
  categories: readonly string[];
  /** Index of the first mark, so the whole chart numbers its marks once. */
  offset: number;
  active: number;
  markProps: (index: number) => MarkProps;
  /** Drawn point diameter. Defaults to the smallest on Crystal's point scale. */
  size?: number;
  /** Draw the point, or only its hit area. A line chart with forty points on it
   *  is a line, not forty dots — but every point is still reachable. */
  visible?: boolean;
}

export function PointMarks({
  points, seriesIndex, seriesName, categories, offset, active, markProps,
  size = chartGeometry.pointMin * 1.5, visible = true,
}: PointMarksProps): ReactNode {
  const marker = seriesMarker(seriesIndex);
  return (
    <>
      {points.map((point, index) => {
        if (!point) return null;
        const at = offset + index;
        return (
          <g
            key={categories[index] ?? index}
            {...markProps(at)}
            role="graphics-symbol"
            aria-label={`${categories[index] ?? index}, ${seriesName}, ${point.label}`}
            className={styles['point']}
            data-active={active === at ? '' : undefined}
            style={{ '--series-colour': seriesColour(seriesIndex) } as CSSProperties}
            transform={`translate(${point.x},${point.y})`}
          >
            {/* The hit area, always. Crystal's action minimum is a promise about
                what a person has to hit, and a six-pixel dot is not it. It is
                invisible and it is not a mark: `pointer-events` is what it is
                for, and a reader is given the shape beside it. */}
            <rect
              className={styles['target']}
              x={-MARK_TARGET / 2}
              y={-MARK_TARGET / 2}
              width={MARK_TARGET}
              height={MARK_TARGET}
            />
            {visible ? <path className={styles['shape']} d={markerPath(marker, size)} /> : null}
          </g>
        );
      })}
    </>
  );
}

/** The stroked path of one series, dashed by its index. */
export function SeriesLine({
  d, seriesIndex, className,
}: { d: string; seriesIndex: number; className?: string }): ReactNode {
  const dash = seriesDash(seriesIndex);
  return (
    <path
      className={[styles['line'], className].filter(Boolean).join(' ')}
      d={d}
      style={{ '--series-colour': seriesColour(seriesIndex) } as CSSProperties}
      {...(dash ? { strokeDasharray: dash } : {})}
    />
  );
}
