/* Fail the build on a hard-coded Crystal value.
 *
 * CONTRACT §1 makes a literal `#7338EF`, `40px` or `1.95px` in library source a
 * defect, because it is a value that can no longer be changed centrally.
 *
 * What is allowed, and why:
 *
 *   - the generated files, which are where values enter;
 *   - 0, 1px and 100%: hairlines, full extents and identity, which nobody would
 *     want to re-theme centrally;
 *   - `transparent`, `currentColor`, `inherit`;
 *   - percentages and unitless numbers, which are usually layout values.
 *
 * Everything else with a unit, and every colour literal, has to come from a
 * token or a custom property.
 *
 *   node scripts/lint-tokens.mjs
 */
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const SRC = join(ROOT, 'src');

/* Generated by build-tokens.mjs; these are the values' point of entry. */
const GENERATED = new Set(['src/styles/_tokens.scss', 'src/theme/tokens.generated.ts']);

/* Values transcribed from a Crystal release the installed package is older than.
 *
 * A file lands here only when Crystal has published a specification this library
 * needs and npm has not caught up, and the alternative to carrying the values is
 * shipping components that do not look like Crystal (R-19). It is a list
 * rather than a per-line exemption so that the set can be counted: each entry is
 * a copy that can go stale and is owed an open issue, and the set should be
 * empty again after the next dependency bump.
 *
 * A file here still owes a header saying which release it was copied from and a
 * test that fails when the installed core starts publishing the values itself. */
const TRANSCRIBED = new Set([]);

const COLOUR = /#[0-9a-fA-F]{3,8}\b|\brgba?\s*\(|\bhsla?\s*\(/;
/* A length with a unit that is not a bare 0 or a 1px hairline. */
const LENGTH = /(?<![\w.$-])(?!0)(\d*\.?\d+)(px|rem|em)(?![\w-])/g;
const ALLOWED_LENGTHS = new Set(['1px', '0px', '2px']);

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (/\.(scss|css|ts|tsx)$/.test(entry)) out.push(full);
  }
  return out;
}

const problems = [];

for (const file of walk(SRC)) {
  const rel = relative(ROOT, file);
  if (GENERATED.has(rel) || TRANSCRIBED.has(rel)) continue;
  const source = readFileSync(file, 'utf8');
  /* Block comments are stripped across the whole file before splitting, because a
     multi-line comment's middle lines carry no delimiter of their own and a value
     mentioned in prose would otherwise be flagged. Newlines are preserved so the
     reported line numbers still point at the real line. */
  const stripped = source.replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '));
  const lines = stripped.split('\n');
  const original = source.split('\n');
  lines.forEach((line, index) => {
    const code = line.replace(/\/\/.*$/, '');
    if (!code.trim()) return;
    /* An explicit, reviewed exception. Written on the line so it is visible in a
       diff rather than buried in this file's allow-list. */
    if (/crystal-allow-literal/.test(original[index] ?? '')) return;

    if (COLOUR.test(code)) {
      problems.push(`${rel}:${index + 1}  colour literal — use a token or custom property\n      ${(original[index] ?? '').trim()}`);
    }
    for (const match of code.matchAll(LENGTH)) {
      const literal = match[1] + match[2];
      if (ALLOWED_LENGTHS.has(literal)) continue;
      problems.push(`${rel}:${index + 1}  length literal "${literal}" — use a token or custom property\n      ${(original[index] ?? '').trim()}`);
    }
  });
}

/* A block comment that never closes, which eats the rules after it.
 *
 * `/*` does not nest, so a comment missing its `*` and `/` runs to the next
 * closing delimiter in the file and deletes every rule in between without any
 * error.
 *
 * No other gate catches it. Comments are stripped before the value check; an
 * unclosed comment is valid CSS, so the compiler accepts it; the types are
 * unaffected; no unit test reads a stylesheet; and the browser gates see only
 * the components they probe.
 *
 * Counting delimiters is a complete check for this: the counts differ only if a
 * comment is unterminated, and an unterminated comment is the only way a rule
 * disappears without anything else noticing.
 */
for (const file of walk(SRC)) {
  if (!/\.(scss|css)$/.test(file)) continue;
  const source = readFileSync(file, 'utf8');
  const opened = (source.match(/\/\*/g) ?? []).length;
  const closed = (source.match(/\*\//g) ?? []).length;
  if (opened !== closed) {
    problems.push(
      `${relative(ROOT, file)}  ${opened} block comment(s) opened and ${closed} closed — `
      + 'an unclosed comment runs to the next one and deletes every rule in between, '
      + 'and nothing else in this repository notices',
    );
  }
}

if (problems.length) {
  console.error(`${problems.length} hard-coded design value(s) — CONTRACT §1:\n`);
  for (const problem of problems) console.error('  - ' + problem);
  console.error('\nValues enter through scripts/build-tokens.mjs. If a literal is genuinely');
  console.error('correct, mark that line `crystal-allow-literal` with a reason beside it.');
  process.exit(1);
}
console.log('No hard-coded design values.');
