/* Fail the build on a hard-coded Crystal value.
 *
 * CONTRACT §1 makes a literal `#7338EF`, `40px` or `1.95px` in library source a
 * defect — not a style preference, a defect, because it is a value that can no
 * longer be changed centrally. A rule nobody checks is a rule that decays, and
 * the design system already learned this the expensive way: its own drift guard
 * exists because prose and tokens had silently diverged.
 *
 * What is allowed, and why:
 *
 *   - the generated files, which are where values legitimately enter;
 *   - 0, 1px and 100% — hairlines, full extents and identity, which are not
 *     design decisions anybody would want to re-theme centrally;
 *   - `transparent`, `currentColor`, `inherit`;
 *   - percentages and unitless numbers, which are usually layout rather than
 *     design values.
 *
 * Everything else with a unit, and every colour literal, has to come from a
 * token or a custom property.
 *
 *   node scripts/lint-tokens.mjs
 */
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const SRC = join(ROOT, 'src');

/* Generated by build-tokens.mjs; these are the values' point of entry. */
const GENERATED = new Set(['src/styles/_tokens.scss', 'src/theme/tokens.generated.ts']);

const COLOUR = /#[0-9a-fA-F]{3,8}\b|\brgba?\s*\(|\bhsla?\s*\(/;
/* A length with a unit that is not a bare 0 or a 1px hairline. */
const LENGTH = /(?<![\w.$-])(?!0)(\d*\.?\d+)(px|rem|em)(?![\w-])/g;
const ALLOWED_LENGTHS = new Set(['1px', '0px', '2px']);

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (/\.(scss|css|ts|tsx)$/.test(entry)) out.push(full);
  }
  return out;
}

const problems = [];

for (const file of walk(SRC)) {
  const rel = relative(ROOT, file);
  if (GENERATED.has(rel)) continue;
  const source = readFileSync(file, 'utf8');
  /* Block comments are stripped across the whole file before splitting, because a
     multi-line comment's middle lines carry no delimiter of their own — the first
     version flagged a value mentioned in prose. Newlines are preserved so the
     reported line numbers still point at the real line. */
  const stripped = source.replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '));
  const lines = stripped.split('\n');
  const original = source.split('\n');
  lines.forEach((line, index) => {
    const code = line.replace(/\/\/.*$/, '');
    if (!code.trim()) return;
    /* An explicit, reviewed exception. Written on the line so it is visible in a
       diff rather than buried in this file's allow-list. */
    if (/crystal-allow-literal/.test(original[index] ?? '')) return;

    if (COLOUR.test(code)) {
      problems.push(`${rel}:${index + 1}  colour literal — use a token or custom property\n      ${(original[index] ?? '').trim()}`);
    }
    for (const match of code.matchAll(LENGTH)) {
      const literal = match[1] + match[2];
      if (ALLOWED_LENGTHS.has(literal)) continue;
      problems.push(`${rel}:${index + 1}  length literal "${literal}" — use a token or custom property\n      ${(original[index] ?? '').trim()}`);
    }
  });
}

/* A block comment that never closes, which eats the rules after it.
 *
 * `/*` does not nest, so a comment missing its `*` and `/` runs to the *next*
 * closing delimiter in the file and silently deletes every rule in between. It
 * happened twice in one sitting, both times while rewriting a comment above a
 * rule: `DataTable.module.scss` lost its entire header, cell, row, checkbox and
 * resizer styling, and `Button.module.scss` lost only comment text because the
 * next `*` and `/` happened to fall before the next rule.
 *
 * Every existing gate passed. Comments are stripped before the value check
 * below; the compiler is happy, because an unclosed comment is valid CSS; the
 * types are unaffected; no unit test reads a stylesheet; and the browser gates
 * probed other components. What found it was opening the page in a browser and
 * measuring a header that was 28px tall with 1px of padding — the user agent's
 * defaults, showing through where the rule should have been.
 *
 * Counting delimiters is a complete check for this: the count can only differ
 * if a comment is unterminated, and an unterminated comment is the only way a
 * rule disappears without anything else noticing.
 */
for (const file of walk(SRC)) {
  if (!/\.(scss|css)$/.test(file)) continue;
  const source = readFileSync(file, 'utf8');
  const opened = (source.match(/\/\*/g) ?? []).length;
  const closed = (source.match(/\*\//g) ?? []).length;
  if (opened !== closed) {
    problems.push(
      `${relative(ROOT, file)}  ${opened} block comment(s) opened and ${closed} closed — `
      + 'an unclosed comment runs to the next one and deletes every rule in between, '
      + 'and nothing else in this repository notices',
    );
  }
}

if (problems.length) {
  console.error(`${problems.length} hard-coded design value(s) — CONTRACT §1:\n`);
  for (const problem of problems) console.error('  - ' + problem);
  console.error('\nValues enter through scripts/build-tokens.mjs. If a literal is genuinely');
  console.error('correct, mark that line `crystal-allow-literal` with a reason beside it.');
  process.exit(1);
}
console.log('No hard-coded design values.');
