/* Regenerate Slice R in docs/implementation-plan.md from Crystal's task data.
 *
 * Slice R's tasks, and the decisions they wait on, live in the sibling Crystal
 * checkout: `proposals/2026-10-02-media-text-and-recipe-parity/tasks.json` and
 * `rulings.json`. When a ruling is recorded there (on the tasks page, or with
 * its `apply-rulings.mjs`), statuses change and tasks are added or dropped.
 * This writes the same effective state into the plan, between the
 * `slice-r` markers, so the plan the implementers read follows the rulings.
 * It reads Crystal as `audit-recipes.mjs` and `build-manifest.mjs` do, and
 * writes only this repository's plan.
 *
 *   pnpm run sync:slice-r
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const LIB = resolve(ROOT, '../crystal-design-system/proposals/2026-10-02-media-text-and-recipe-parity/rulings-lib.mjs');
const PLAN = join(ROOT, 'docs/implementation-plan.md');

if (!existsSync(LIB)) {
  console.error(`Cannot find Crystal's task data at ${LIB}. Check out crystal-design-system beside this repository.`);
  process.exit(1);
}
const { load, effective } = await import(pathToFileURL(LIB).href);
const { data, record } = load();
const { tasks, decisions } = effective(data, record);

const STATE = { blocked: ' Blocked.', ruling: ' Needs a ruling.', dropped: ' Dropped by a ruling.' };
const lines = [
  '### R: Media, text and recipe parity', '',
  'Added 2 October 2026 from Meridian\'s brief of that day. The proposal is',
  '[`proposals/2026-10-02-media-text-and-recipe-parity.md`](proposals/2026-10-02-media-text-and-recipe-parity.md);',
  'Crystal\'s half, with the findings, the core recipes and the decisions D-30 to D-35, is',
  '`crystal-design-system/proposals/2026-10-02-media-text-and-recipe-parity.md`. The tasks',
  'below are generated by `pnpm run sync:slice-r` from that proposal\'s `tasks.json` and',
  '`rulings.json`, where each also carries its acceptance checks; the IDs are shared with',
  'Crystal\'s task board, where rulings are recorded.', '',
  'The slice changes no component count. It gives the media players, the rich text',
  'surface and `Prose` the anatomy the catalogue now specifies, makes every motion',
  'recipe visible, credits motion a child plays, and measures the library against',
  'the catalogue so the remaining material work can be counted.', '',
];
const ruled = decisions.filter((d) => d.state === 'ruled');
lines.push(ruled.length
  ? `Rulings in force: ${ruled.map((d) => `${d.id} (${d.ruling.option}), ${d.ruling.date}`).join('; ')}. The record is \`crystal-design-system/proposals/2026-10-02-rulings.md\`.`
  : 'No decision has been ruled yet; the record will be `crystal-design-system/proposals/2026-10-02-rulings.md`.', '');

const areas = new Map();
for (const task of tasks.filter((t) => t.repo === 'react')) {
  if (!areas.has(task.area)) areas.set(task.area, []);
  areas.get(task.area).push(task);
}
for (const [area, list] of areas) {
  lines.push(`**${area}**`, '');
  for (const task of list) {
    const box = task.status === 'done' ? 'x' : ' ';
    const waits = task.depends.length ? ` Waits on ${task.depends.join(', ')}.` : '';
    const by = task.ruledBy ? ` By the ruling on ${task.ruledBy.decision}.` : '';
    lines.push(`- [${box}] **${task.id}** (${task.priority}) ${task.title}. ${task.target}${waits}${STATE[task.status] ?? ''}${by}`);
  }
  lines.push('');
}

const plan = readFileSync(PLAN, 'utf8');
const marker = /(<!-- slice-r:start[^>]*-->\n)[\s\S]*?(<!-- slice-r:end -->)/;
if (!marker.test(plan)) {
  console.error('docs/implementation-plan.md has no slice-r markers.');
  process.exit(1);
}
const next = plan.replace(marker, `$1${lines.join('\n').trimEnd()}\n$2`);
if (next !== plan) writeFileSync(PLAN, next);
console.log(`Slice R ${next === plan ? 'already current' : 'regenerated'}: ${tasks.filter((t) => t.repo === 'react').length} tasks, ${ruled.length} of ${decisions.length} decisions ruled.`);
